//图标库对应json
var icon={[{
	'icon-home':'e追溯',
	'icon-code-rule':'解码规则管理',
	'icon-goods-manager':'追溯信息管理',
	'icon-traces-search':'追溯查询',
	'icon-code-manager':'追溯节点管理',
	'icon-traces-log':'追溯查询日志',
	'icon-traces-mobile-search':'移动端追溯查询'
	}],
	[{
		'icon-traces-msg-manager':'信息管理',
		'icon-code-save':'节点备案',
		'icon-code-type':'上传节点类型管理',
		'icon-code-with':'节点对照管理',
		'icon-code-record':'商户备案管理',
		'icon-work-save':'节点保存管理',
		'icon-work':'作业信息管理',
		'icon-data-manager':'数据源信息管理',
		'icon-data-clean':'清洗作业信息管理',
		'icon-data-clean-manager':'数据清洗管理',
	}],
	[{
		'icon-log-manager':'日志管理',
		'icon-acute':'方法异常日志管理',
		'icon-log-search':'日志查询',
		'icon-log-resolve':'文件解析日志管理',
	}],
	[{
		'icon-data-search':'数据查询',
		'icon-data-with':'本地与新大陆数据'
	}],
	[{
		'icon-mail-manager':'邮件管理',
		'icon-mail-type':'邮件类型管理',
		'icon-mail-user':'邮件人员管理'
	}],
	[{
		'icon-analyse':'运行分析',
		'icon-company-analyse':'企业分析',
		'icon-tenants-analyse':'商户分析'
	}],
	[{
		'icon-settings':'系统设置',
		'icon-client-manager':'用户管理',
		'icon-function-manager':'功能管理',
		'icon-level-manager':'角色权限管理'
	}]
}
